#ifndef SCANNERH
#define SCANNERH

typedef enum TOKEN {
    FDT,
    ENTERO, LEER, ESCRIBIR, PROGRAMA, FIN_PROGRAMA,
    IDENTIFICADOR,
    CONSTANTE,
    ASIGNACION,
    OP_SUMA, OP_RESTA, OP_MULTIPLICACION, OP_DIVISION, OP_PORCENTAJE,
    COMA, PAREN_IZQ, PAREN_DER, PUNTO_COMA,
} token;

#endif
